apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressapi
  namespace: api
spec:
  entryPoints:
    - web
  routes:
  - match: host(`api.143.244.208.103.nip.io`)
    kind: Rule
    services: 
    - name: api-service
      port: 80
