apiVersion: v1
kind: Deployment
metadata:
  name: pegelogo
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pegelogo
  template:
    metadata:
      labels:
        app: pegelogo
    spec:
      containers:
      - name: pegelogo
        image: acthiago/api-pedelogo:{{tag}}
      
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: Mongo__Host
            value: "mongo-service"
          - name: Mongo__Port
            value: "27017"
          - name: Mongo__DataBase
            value: "admin"
        envFrom:
          - configMapRef:
              name: configmap-mongodb

        