apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dci-pvc
  namespace: api
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  
