apiVersion: v1
kind: Service
metadata:
  name: mongo-service

spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  - port: 9216
    targetPort: 9216
    name: exporter
  type: ClusterIP
